branches:
  - main
  - name: dev
    channel: dev
    prerelease: dev
tagFormat: ${version}
preset: conventionalcommits
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - presetConfig:
        types:
          - type: "fix"
            section: "Fixes"
          - type: "feat"
            section: "Features"
          - type: "perf"
            section: "Performance Improvements"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: uv version "${nextRelease.version}"
      publishCmd: uv build
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - pyproject.toml
        - uv.lock
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - "@semantic-release/github"
