branches:
  - main
  - name: dev
    channel: dev
    prerelease: dev
tagFormat: ${version}
preset: conventionalcommits
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - presetConfig:
        types:
          - type: "fix"
            section: "Fixes"
          - type: "feat"
            section: "Features"
          - type: "perf"
            section: "Performance Improvements"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: |
        python -c "import re; content = open('jsonpath/__init__.py').read(); open('jsonpath/__init__.py', 'w').write(re.sub(r'__version__ = \".*?\"', '__version__ = \"${nextRelease.version}\"', content))"
        uv version "${nextRelease.version}"
      publishCmd: uv build
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - jsonpath/__init__.py
        - pyproject.toml
        - uv.lock
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - "@semantic-release/github"
